apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fiap-games
  labels:
    app: prometheus
    tier: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'catalog-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['catalog-api:80']

      - job_name: 'usuarios-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['user-api:80']

      - job_name: 'payment-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['payment-api:80']

      - job_name: 'notifications-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['notification-api:80']
