# ATENÇÃO: Em produção, use Sealed Secrets, External Secrets Operator ou Vault.
# Nunca commite este arquivo com credenciais reais.
apiVersion: v1
kind: Secret
metadata:
  name: infra-secret
  namespace: fiap-games
  labels:
    tier: infrastructure
type: Opaque
stringData:
  # SQL Server
  MSSQL_SA_PASSWORD: "PosTech@123"

  # MongoDB
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "PosTech@123"

  # Keycloak PostgreSQL
  KEYCLOAK_POSTGRES_DB: "keycloak"
  KEYCLOAK_POSTGRES_USER: "keycloak"
  KEYCLOAK_POSTGRES_PASSWORD: "keycloak"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
