apiVersion: v1
kind: Secret
metadata:
  name: notification-api-secret
  namespace: fiap-games
  labels:
    app: notification-api
type: Opaque
stringData:
  MongoDb__Username: "admin"
  MongoDb__Password: "PosTech@123"
