apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secret
  namespace: fiap-games
  labels:
    app: payment-api
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PaymentAPI;User Id=sa;Password=PosTech@123;TrustServerCertificate=True"
  MongoDb__Username: "admin"
  MongoDb__Password: "PosTech@123"
