apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fiap-games
  labels:
    app: catalog-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Kafka__GroupId: "catalog-api-group"
  MongoDb__DatabaseName: "CatalogAudit"
