apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-api-config
  namespace: fiap-games
  labels:
    app: notification-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Kafka__GroupId: "notification-api-group"
  MongoDb__DatabaseName: "NotificationAudit"
