apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-api-config
  namespace: fiap-games
  labels:
    app: payment-api
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Kafka__GroupId: "payment-api-group"
