apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-config
  namespace: fiap-games
  labels:
    app: user-api
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Kafka__GroupId: "usuarios-api-group"
  Keycloak__Authority: "http://keycloak:80/realms/TechChallengeFiap"
  Keycloak__Audience: "tech-challenge"
  Keycloak__BaseUrl: "http://keycloak:80/"
  Keycloak__Realm: "TechChallengeFiap"
  Keycloak__ClientId: "tech-challenge"
