apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: fiap-games
  labels:
    app: keycloak-postgres
    tier: infrastructure
spec:
  selector:
    app: keycloak-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
