apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: fiap-games
  labels:
    app: mongodb
    tier: infrastructure
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
