apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: fiap-games
  labels:
    app: sqlserver
    tier: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secret
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          readinessProbe:
            exec:
              command:
                - /opt/mssql-tools18/bin/sqlcmd
                - -S
                - localhost
                - -U
                - sa
                - -P
                - "PosTech@123"
                - -Q
                - "SELECT 1"
                - -No
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: sqlserver-pvc
