apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: fiap-games
  labels:
    app: catalog-api
    tier: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: fiap/catalog-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            # ConfigMap compartilhado (Kafka topics, Redis, MongoDB host)
            - configMapRef:
                name: shared-infra-config
            # ConfigMap específico (GroupId, DatabaseName, env)
            - configMapRef:
                name: catalog-api-config
            # Secret (connection strings, senhas)
            - secretRef:
                name: catalog-api-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
