# Placeholder — descomentar quando FIAP.PaymentAPI for criado
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: fiap-games
  labels:
    app: payment-api
    tier: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: payment-api
          image: fiap/payment-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: shared-infra-config
            - configMapRef:
                name: payment-api-config
            - secretRef:
                name: payment-api-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
